#!/usr/bin/env python3
"""Generate a Traditional-Chinese token blocklist for a specific Whisper vocab.

`find_traditional_tokens.py` is hard-wired to the Tiny vocab. Whisper-Large-V3
tokenizes Chinese differently, so reusing Tiny token IDs on Turbo would mask
unrelated tokens. This reuses that script's decoder + character table but takes
an explicit vocab path and Kotlin object name.

    python gen_blocklist.py --vocab <vocab.json> --object TraditionalChineseBlocklistTurbo
"""
from __future__ import annotations

import argparse
import importlib.util
import json
import sys
from pathlib import Path


def load_reference_module():
    path = Path(__file__).with_name("find_traditional_tokens.py")
    spec = importlib.util.spec_from_file_location("find_traditional_tokens", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def collect_ids(module, vocab_path: Path):
    with open(vocab_path, "r", encoding="utf-8") as handle:
        vocab = json.load(handle)
    ids = []
    for raw_token, token_id in vocab.items():
        decoded = module.decode_token(raw_token)
        if not decoded or decoded.startswith("<|"):
            continue
        if module.contains_traditional(decoded):
            ids.append(token_id)
    return sorted(set(ids))


def render(module, object_name: str, vocab_path: Path, ids) -> str:
    ids_str = ", ".join(str(x) for x in ids)
    return f"""package com.example.whisperapp.asr

/**
 * Auto-generated blocklist of token IDs containing Traditional Chinese characters.
 * Generated by tools/gen_blocklist.py from {vocab_path.name} of this variant's vocab.
 *
 * When filtering logits, mask these token IDs to force Simplified Chinese output.
 * Token IDs are vocab-specific: Whisper-Large-V3 does not share Tiny's Chinese merges.
 * Total: {len(ids)} tokens
 */
object {object_name} {{
    /** Set of token IDs that decode to text containing Traditional Chinese characters. */
    val blockedTokenIds: Set<Int> = setOf({ids_str})

    /** Check if a token ID should be blocked. */
    fun isBlocked(tokenId: Int): Boolean = tokenId in blockedTokenIds
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--vocab", required=True)
    parser.add_argument("--object", required=True)
    parser.add_argument("--out", required=True)
    parser.add_argument("--compare", default=None, help="optional legacy .kt file to diff against")
    args = parser.parse_args()

    module = load_reference_module()
    vocab_path = Path(args.vocab)
    ids = collect_ids(module, vocab_path)
    Path(args.out).write_text(render(module, args.object, vocab_path, ids), encoding="utf-8")
    print(f"{args.object}: {len(ids)} blocked token ids -> {args.out}", file=sys.stderr)

    if args.compare:
        import re
        text = Path(args.compare).read_text(encoding="utf-8")
        match = re.search(r"setOf\(([^)]*)\)", text)
        legacy = {int(x) for x in match.group(1).split(",") if x.strip()} if match else set()
        current = set(ids)
        print(
            f"compare vs {Path(args.compare).name}: legacy={len(legacy)} "
            f"shared={len(legacy & current)} only-new={len(current - legacy)} only-legacy={len(legacy - current)}",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
